import json
import sqlite3

DB_PATH = "hl7_data_lake.db"

def init_db():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Patients table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS patients (
        patient_id INTEGER PRIMARY KEY AUTOINCREMENT,
        mrn TEXT UNIQUE NOT NULL,
        name TEXT NOT NULL,
        dob TEXT,
        gender TEXT
    );
    """)
    
    # Observations table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS observations (
        observation_id INTEGER PRIMARY KEY AUTOINCREMENT,
        mrn TEXT NOT NULL,
        test_name TEXT NOT NULL,
        value REAL,
        unit TEXT,
        flag TEXT,
        timestamp TEXT,
        FOREIGN KEY (mrn) REFERENCES patients(mrn)
    );
    """)
    
    conn.commit()
    conn.close()

def load_json_data(json_data):
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Ingest Patients
    for patient in json_data.get("patients", []):
        cursor.execute("""
        INSERT INTO patients (mrn, name, dob, gender)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(mrn) DO UPDATE SET
            name=excluded.name,
            dob=excluded.dob,
            gender=excluded.gender;
        """, (patient["mrn"], patient["name"], patient["dob"], patient["gender"]))
        
    # Ingest Observations
    for obs in json_data.get("observations", []):
        # We let SQLite handle auto-incrementing the primary key, 
        # but link it to the correct patient via MRN
        cursor.execute("""
        INSERT INTO observations (mrn, test_name, value, unit, flag, timestamp)
        VALUES (?, ?, ?, ?, ?, ?);
        """, (obs["mrn"], obs["test_name"], obs["value"], obs["unit"], obs["flag"], obs["timestamp"]))
        
    conn.commit()
    conn.close()
    print("Successfully loaded parsed data into SQLite!")

def verify_data():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    print("\n--- Patients Table ---")
    cursor.execute("SELECT * FROM patients;")
    for row in cursor.fetchall():
        print(row)
        
    print("\n--- Observations Table ---")
    cursor.execute("SELECT * FROM observations;")
    for row in cursor.fetchall():
        print(row)
        
    conn.close()

if __name__ == "__main__":
    # The JSON output generated by your Omni-Logger test
    parsed_output = {
        "patients": [
            {"patient_id": 1, "mrn": "MRN998877", "name": "ALEX JARECKI", "dob": "1992-05-15", "gender": "M"}
        ],
        "observations": [
            {"observation_id": 1, "mrn": "MRN998877", "test_name": "Cholesterol, Total", "value": 210, "unit": "mg/dL", "flag": "H", "timestamp": "2026-06-25 10:30:00"},
            {"observation_id": 2, "mrn": "MRN998877", "test_name": "Triglycerides", "value": 150, "unit": "mg/dL", "flag": "N", "timestamp": "2026-06-25 10:30:00"},
            {"observation_id": 3, "mrn": "MRN998877", "test_name": "Cholesterol in LDL", "value": 125, "unit": "mg/dL", "flag": "H", "timestamp": "2026-06-25 10:30:00"},
            {"observation_id": 4, "mrn": "MRN998877", "test_name": "Cholesterol in HDL", "value": 45, "unit": "mg/dL", "flag": "N", "timestamp": "2026-06-25 10:30:00"}
        ]
    }
    
    init_db()
    load_json_data(parsed_output)
    verify_data()
